# Basic Information 
title: Changfu Jia
# subtitle:
position: Ph.D candidate (2024 fall)
# subposition: Chair of the Chinese Student and Scholar Association (CSSA)
affiliation: University of British Columbia
subaffiliation: Zoology
#affiliation_link: https://www.nyu.edu
#subaffiliation_link: https://med.nyu.edu/research/vilcek-institute-graduate-biomedical-sciences/
email: jiachangfu777@126.com
#address: 180 Madision Ave, Suite 5-31C, New York, NY 10016
#address_link: https://goo.gl/maps/aQZfmiKjQmqbDsVY9



# 搜索引擎优化 (SEO)
keywords: minimal light
description: 在这里输入网页描述.
canonical: https://minimal-light-theme.yliu.me/

# 链接
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=hW83xEsAAAAJ&view_op=list_works&sortby=pubdate
#cv_link: files/Curriculum_Vitae.pdf
github_link: https://github.com/bilibilij/
#linkedin: https://www.linkedin.com/
#twitter: https://twitter.com/
#researchGate: https://www.researchgate.net/profile/Changfu-Jia
researchGate: https://www.researchgate.net/profile/Changfu-Jia


# 图片路径
avatar: ./assets/img/personal.jpg
favicon: ./assets/img/Guppy_cartoon4.png
favicon_dark: ./assets/img/Guppy_cartoon4.png

# Google Analytics ID
google_analytics: UA-111540567-4


# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
